apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense-1
spec:
  selector:
    component: backend
    project: expense-1
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port